### ISSUE TITLE
Getting an 404 error 

### ISSUE THREAD

**Issue by vibhi19** [littlebizzy/slickstack#1]
Hi I wanted to use Slick stack but when i put your command it show 404 erro

**Comment by jessuppi** [comment]
Sorry for the late reply here, I guess it was during our early alpha when things were pretty messy. The below shortcut link should now always load the latest ss-install.txt mirror file:

http://slick.fyi

e.g.

    sudo wget -O ss slick.fyi && sudo bash ss

**Comment by vibhi19** [comment]
Thanks will use it for next project
