### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by wkk5** [littlebizzy/slickstack#10]
First several attempted installs was on Vultr droplet with 2048 MB Memory using Ubuntu 18.04, but the nginx install seemed to fail and service wouldn't start.  I followed the instructions on the readme and did a "sudo reboot" after the install.  I reattempted 3x on separate droplets and got this error in nginx log:

2019/05/23 01:03:39 [emerg] 15746#15746: invalid number of arguments in "return" directive in /etc/nginx/sites-enabled/default:21

I fixed some lines with ";" issues in that default file, but then got this error:

2019/05/23 04:00:27 [emerg] 1542#1542: BIO_new_file("/etc/ssl/nginx.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

After that I decided to try installing on Vultr droplet with 2048 MB Memory using Ubuntu 16.04, This time, there was no nginx error during the installation!  On restart, it didn't look like the nginx service started, so I started it "service nginx restart"  Once started, the site is now showing a 502 Bad Gateway error.  Here is the nginx error logs:

from /var/log/nginx/:
2019/05/23 04:26:10 [info] 14999#14999: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:184
2019/05/23 04:27:10 [info] 25663#25663: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:184
2019/05/23 04:30:31 [info] 2308#2308: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:184
2019/05/23 04:30:46 [info] 2338#2338: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:184
2019/05/23 04:36:58 [info] 2297#2297: Using 32768KiB of shared memory for nchan in /etc/nginx/nginx.conf:184

from /var/www/logs/:
2019/05/23 04:30:55 [crit] 2347#2347: *5 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "xxx.xxx.com"
2019/05/23 04:31:03 [crit] 2347#2347: *5 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.com, request: "GET /wp-admin/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "xxx.xxx.com"
2019/05/23 04:37:09 [crit] 2304#2304: *5 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "xxx.xxx.com"
2019/05/23 04:47:01 [crit] 2304#2304: *11 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "xxx.xxx.com"

Other info:
ss-config updated following comments in file and made sure to set up Cloudflare api as well as point cloudflare to vultr droplet

Any suggestions?

**Comment by jessuppi** [comment]
If you want to get involved here, setup a real profile and show everyone you're serious...

**Comment by wkk5** [comment]
Hi Jesse,

I don't understand your comment... I am serious and I did read your documentation and follow it very carefully, unlike some of the other tickets that were submitted where you did respond to.  I'm sorry if I offended you in any way, but I was directed here by reddit posts that recommended slickstack.  I'm interested in learning and researching about running my own wordpress server, and submitted a ticket because the install is not working despite following the instructions.  Anyway, just want you know that your work is appreciated, and any advice you have would be very helpful.

**Comment by jessuppi** [comment]
I'm not chatting with anons who create throwaway accounts to ask for free support. If you're a developer than create a real GitHub profile and get involved. If you're not, become a paying member:

https://www.littlebizzy.com/members

**Comment by wkk5** [comment]
Sorry, I'm new to Github and didn't know that having a profile was so important.  I've just updated my profile.  Could you please kindly re-open my ticket?  I've been researching Centminmod also, and saw your posts in that forum.  Interested in comparing different LEMP solutions (EasyEngine, etc.), and Slickstack has been mentioned alot on the internet.

**Comment by jessuppi** [comment]
Thank you --

> 2019/05/23 01:03:39 [emerg] 15746#15746: invalid number of arguments in "return" directive in /etc/nginx/sites-enabled/default:21

Seems like your domain is not defined properly in ss-config maybe and/or:

> 2019/05/23 04:00:27 [emerg] 1542#1542: BIO_new_file("/etc/ssl/nginx.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/nginx.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)

> 2019/05/23 04:30:55 [crit] 2347#2347: *5 connect() to unix:/run/php/php7.2-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: xxx.xxx.xxx.xxx, server: xxx.xxx.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "xxx.xxx.com"

Hard to say but Nginx did not setup correctly seems. This can be from the host's mirrors timing out and not downloading properly, or a typo, or other circumstantial errors.

Sometimes trying a different datacenter or even a new physical node (IP) can resolve it.

If it works elsewhere, then it's circumstantial (temporary).

**Comment by wkk5** [comment]
Thanks for the response! 

I'll spin up another node and give it one more go tonight.
