### ISSUE TITLE
Nginx core packages are not being installed during ss-install

### ISSUE THREAD

**Issue by aminmaster** [littlebizzy/slickstack#101]
Just installed on a fresh Ubuntu 20.4 and could not access the website. Upon investigation found that the script fails to install nginx completely. Tried to install with "sudo bash /var/www/ss-install-nginx-ssl" and it gave the following message.

Running ss-install-nginx-ssl: Reinstalls desired SSL cert (OpenSSL vs Lets Encrypt) to Nginx (idempotent)... 
cp: cannot create regular file '/etc/nginx/conf.d/openssl.conf': No such file or directory
OpenSSL installation appears to have been successful. 
Running ss-perms-nginx-ssl: Resets all file and user permissions for SSL certs and related Nginx files... 
chmod: cannot operate on dangling symlink '/var/www/certs/cert.pem'
chmod: cannot operate on dangling symlink '/var/www/certs/chain.pem'
chmod: cannot operate on dangling symlink '/var/www/certs/fullchain.pem'
chmod: cannot operate on dangling symlink '/var/www/certs/keys/privkey.pem'

Listing of the certs directory

total 16
drwxr-xr-x  3 root root 4096 May 20 06:25 .
drwxr-xr-x 10 root root 4096 May 20 06:44 ..
lrwxrwxrwx  1 root root   41 May 20 06:25 cert.pem -> /etc/letsencrypt/live/slickstack/cert.pem
lrwxrwxrwx  1 root root   42 May 20 06:25 chain.pem -> /etc/letsencrypt/live/slickstack/chain.pem
lrwxrwxrwx  1 root root   46 May 20 06:25 fullchain.pem -> /etc/letsencrypt/live/slickstack/fullchain.pem
drwx------  2 root root 4096 May 20 06:25 keys
-rw-r--r--  1 root root 1371 May 20 06:25 slickstack.crt

Please advise

**Comment by jessuppi** [comment]
Thanks for reporting @aminmaster 

We changed a few filenames and forgot to update `ss-install` yesterday, now it's fixed: https://github.com/littlebizzy/slickstack/commit/e79d85bb113e44cd7bb893bc98958958d996cfa4
