### ISSUE TITLE
Can Not Install On Oracle Instance

### ISSUE THREAD

**Issue by miketester19** [littlebizzy/slickstack#104]
Hello SlickStack;

The script wont work on Oracle Instance.. I tried to Install but it delivered some errors then stopped. It seems to me that Oracle won't allow root logon as you probably already know. 
Please help.

Suggestion: Please leave root enable / disable option open.
Thanks

**Comment by jessuppi** [comment]
Hello @miketester19 

We only support KVM machines on Ubuntu LTS, I'm not sure what server/platform you're using. Why don't you try a more user-friendly platform like DigitalOcean, Vultr, Hostwinds, Linode, UpCloud, etc?

What errors do you see, please be specific?

SlickStack shouldn't necessarily require the `root` user, it can run the `/var/www/ss-install` using `sudo` as well.

**Comment by miketester19** [comment]
It means you are not familiar with Oracle Instance, that's strange, Oracle Instance just like Vultr, Linode and Digitaloceans, its VPS.
And Yes, I tried on Vutlr as well, and ended up with invalid SSL, I added the Cloudflare API Key as required, and email etc,
Anyways thanks

**Comment by jessuppi** [comment]
Yes as per our documentation we prioritize independent user-friendly clouds, not enterprise (corporate) clouds. If you don't really know what you're doing, I'm not sure why you'd choose such an advanced cloud partner.

Please keep each Issue focused on a specific topic, SSL is off-topic here, thanks!

**Comment by miketester19** [comment]
Hello Jessuppi;
Thanks for your response and I got it working on Oracle Instance (VPS). It was my fault, I was distracted with some thing else.
But got it working and this proves The Best Script of All, The SlickStack works on  Oracle Instance as well, as it does on vultr, digitaloceans etc.

Thanks

**Comment by jessuppi** [comment]
@miketester19 Okay great, can you please specify what you did to make it work properly on your Oracle instance?
