### ISSUE TITLE
SlickStack Issues Please Help

### ISSUE THREAD

**Issue by miketester19** [littlebizzy/slickstack#105]
Hello SlickStack;

First of all let me thank you for creating such a great script, but as it provide the best security and optimization, but it's also a very hard to work with. 
Issue no 1. It disables the root access, now most of the configuration require root access, I've tested SlickStack with Vultr and Oracle.
It won't work with Oracle Instances, Since oracle won't allow root login, and script failed to install, If there is work around please help.
Issue 2. After Installing WordPress , Cloudflare delivered the error 526, Invalid SSL. Now I tried to install my Cloudflare SSL but , keep getting error chmod not simlinking like that, I mean after installing , the slickstack loose the access by it Self..

Please make it user friendly and at least leave the Root access Enable or Disable option open.

Note: I want to add subdomain forum.example.com, How can I do that
Please help'

Thanks & Regards

**Comment by jessuppi** [comment]
Hello @miketester19 

Thanks for your kind words, but this is not a Support forum. Please refrain from opening multiple Issues:

https://github.com/littlebizzy/slickstack/issues/104

I will close this Issue and please continue the conversation on your first Issue above. You can ask general "how to" questions on our community forums like Discord, etc.
