### ISSUE TITLE
ss-install-mysql-packages wrong call to ss-perms-mysql

### ISSUE THREAD

**Issue by gingibash** [littlebizzy/slickstack#107]
on line 237 calls ```source /var/www/ss-perms-mysql``` instead of ```source /var/www/ss-perms-mysql-packages```

**Comment by jessuppi** [comment]
Thanks for reporting @gingibash 

This is now fixed: https://github.com/littlebizzy/slickstack/commit/9cbb0128547ac35eca034b13e3b57e24db8cd6d6
