### ISSUE TITLE
How  To Install WordPress With SlickStack On Oracle Instance Plus ss-config

### ISSUE THREAD

**Issue by miketester19** [littlebizzy/slickstack#108]
Hello SlickStack;
Your Script is most optimized and Secured for Installing LEMP and WordPress, and also Most difficult, to Install, configure. It won't work on Oracle Instance. I tried three times on Vultr, and ended up with Invalid SSL, and Plus there is no option for sub domains, If I add sub domain it will create, a file in sites-available, like, example.com|blog.example.com.
Secondly how to configure ss-config for manual installation. I tried with @ sigh, without @sign and always ended up, getting error you ss-config is not configure.. Please give us exact example, like  Root use "@Root_User"  Now what should we put here..

Please make is more user friendly.

Thnaks

**Comment by jessuppi** [comment]
You've already opened an Issue on the same topic, please leave any related comments on that page. You clearly have not reviewed our documentation or the Installation page on our website:

https://slickstack.io/install
https://slickstack.io/requirements

Please refrain from dumping laundry lists of complaints without specific technical questions or error messages.

**Comment by miketester19** [comment]
Hello Jesse;
First of all let me thank you for creating such a great script, Secured and Optimized, the best script I ever seen, I've tested all the scripts, and I found, SlickStack The Best Script. We all appreciate your efforts and hard work for providing us such a great script.
Secondly, Jesse; I'm having problem reinstalling WordPress with SlockStack, I'm getting error, more headers , nginx.conf, when I fixed that I start getting an other erros, rt-session etc. It seems to me, that there were some files left, when I uninstall every thing including ss.
Jesse, how to uninstall SlickStack completely if we have to reinstall WordPress With slickstack. Because some times things go wrong, and it need to be reinstalled, so question is, How to completely remove SlickStack, so it allows us to reinstall WordPress with slickstack again, I mean the clean install.
Secondly I'm having big time problem running screen, Because I'm running CloudBot and that requires screen program, other wise cloudbot gets disconnected when I close the terminal.
But when ever I tried running cloudbot with screen, I get screen is terminating.

Please help..
Thanks & Regards

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jessuppi** [comment]
@miketester19 Thanks for your kinds words, but this is not for general support (it is for bug reports or feature requests). If you have general questions you need to join our community chat rooms like Discord, etc.

Link to your other Issue: https://github.com/littlebizzy/slickstack/issues/104

I'm locking this thread to prevent further discussion here.
