### ISSUE TITLE
White label integration in SlickStack dashboard and drop-down

### ISSUE THREAD

**Issue by bari86** [littlebizzy/slickstack#111]
Since white-label is there, these things might need to be looked at:
a) 'SlickStack Settings (Under Constructions)' title to change to something we can define.
b) On the same menu, for the 'SlickStack Build' to probably just 'Build'? or something that we can define.
c) Disable the top bar menu for SlickStack? And possible to change to something that we can define too, like 'Build using SS'.

**Comment by jessuppi** [comment]
Okay @bari86  I've added this in part: https://github.com/littlebizzy/slickstack/commit/10a2a10ced7fad63b4b849e82e9f4d734e2cd828

However, not sure about changing the "build" as it wouldn't really have any meaning to say "ACME Agency Build"... and we probably want to keep a mention of SlickStack at least somewhere small.

About the top bar menu, we will have to think more about how to handle disabling that or modifying that.

**Comment by bari86** [comment]
wow. I have already seen the changes in (a) in my new site.

For the (b), still fine actually. leave as it is?

For the (c), if you can move to top right would be good too? I am just used to use top left to view homepage and yours is there. maybe create an option to choose left or right?

**Comment by jessuppi** [comment]
I don't think there's any point to changing the top menu drop-down to the right side, we are emulating WordPress Core which only displays their drop-down menu on the top left, no matter what. Disabling it might be an option.

**Comment by jessuppi** [comment]
An update on this:

We have gone ahead and totally removed the top bar menu (drop-down) on our xxx-common.php MU plugin just to keep things a bit cleaner and more standard, and to avoid confusing users.

For now we will not allow customizing the `SS_BUILD` phrase in the SlickStack dashboard, but anyone can comment on this Issue in the future to continue this discussion, thanks!
