### ISSUE TITLE
Staging / Dev disabled

### ISSUE THREAD

**Issue by bari86** [littlebizzy/slickstack#112]
I disabled staging & development install. But on the top bar menu, the green test saying 'Production', there are still 2 dropdown saying switch to staging/dev. If a user click it, it will go to 404 page as it was disabled in the first place. Can you make a different text such as Staging disabled. Dev disabled. Or something showing it is disabled?

**Comment by jessuppi** [comment]
Thanks for the suggestion @bari86 

This has now been fixed, and the Staging/Dev/Production links are now properly mirrored to be more useful.

Hope you like it, and if you're still willing to review SlickStack on Capterra we'd appreciate it ;)
