### ISSUE TITLE
AUG2021C - cannot install

### ISSUE THREAD

**Issue by bari86** [littlebizzy/slickstack#118]
Hi,
I believe after you update to version AUG2021C, I cannot install it. I tried using my own config file, not working. I then try using without any config file, just the one line install. also not working. it gives tons of this kind of error

`/var/www/ss-config: line 2: $'\r': command not found
/var/www/ss-config: line 13: $'\r': command not found
/var/www/ss-config: line 16: $'\r': command not found

....

/var/www/ss-config: line 738: $'\r': command not found
Exiting ss-install: Please run ss-update-config since your ss-config is outdated and try again...
`

I tried reading the code, it does seem to use the correct build. what is wrong?

**Comment by jessuppi** [comment]
Hello @bari86 sorry but I can't duplicate this after multiple tests.

Based on the information you shared in our chat rooms, it seems like you are using an array of customized / forked SlickStack versions and other custom "hacks", and I can't really understand where the problem(s) originate.

The error you mentioned sounds like a non-Unix file format maybe, or perhaps your ss-config is messed up. Please try to update your ss-config to latest format via `ss-update-config` and then try again.
