### ISSUE TITLE
Blacklist questions

### ISSUE THREAD

**Issue by hxinen** [littlebizzy/slickstack#12]
Hi again, thanks for the amazing updates to slickstack!

I have a question, is there a way to whitelist some plugins that are on the blacklist on a per site basis? There are a few plugins that I would want to use on one install, but just don't know how to whitelist - maybe just by forking?

And curious as to why Studiopress/Genesis themes are not recommend?

====
Oh and what are your thoughts on upcloud.com? We are using it + slickstack, I encountered a lot of installation errors, because of their firewall, but it got sorted out, and works perfectly fine. 
They claim to be
> World's fastest cloud servers

**Comment by jessuppi** [comment]
> I have a question, is there a way to whitelist some plugins that are on the blacklist on a per site basis? There are a few plugins that I would want to use on one install, but just don't know how to whitelist - maybe just by forking?

Correct, no way to whitelist plugins that are banned, and probably a bad idea anyway.

We've thought about supporting custom blacklists, but not really a priority as it's pretty clear which plugins are causing performance and security (or ethical) issues.

> And curious as to why Studiopress/Genesis themes are not recommend?

They are a proprietary framework on top of the WordPress framework, so it's rather like having to learn yet another language when doing any web development. The goal behind SlickStack is simplicity and stability (and standardization) so Genesis is not really in that sphere...

> Oh and what are your thoughts on upcloud.com?

Not really the place for these questions, will try to add more reviews on our homepage.

Please complete your GitHub profile if you want to keep interacting here, our goal is promoting open source on GitHub with real people, not anonymous / faceless thanks...

**Comment by jessuppi** [comment]
Custom plugin backlists are now supported in ss5a, see:

https://github.com/littlebizzy/slickstack/blob/master/ss-config-sample.txt
https://github.com/littlebizzy/slickstack/blob/master/ss-worker.txt

Modify in your `ss-config` file:

    PLUGIN_BLACKLIST_SOURCE="http://mirrors.slickstack.io/wordpress/blacklist.txt"

Ref: https://github.com/littlebizzy/slickstack/commit/7bf8ca4b56d77149fb2bdc2bb7b23a6722f9a995
