### ISSUE TITLE
Production / Staging / Development drop-down malformed URLs

### ISSUE THREAD

**Issue by Syncriix** [littlebizzy/slickstack#121]
Switching from `Production` to `Staging` and `Development` works as intended
![133135683-9bb4fc93-103d-433b-a66a-02b35a5cddbe](https://user-images.githubusercontent.com/25897271/133136289-05a5271e-16ee-4bd3-9bdf-21f206ba847a.png)
Switching from either `Staging` or `Development` to either availible options
![133135796-9a31361b-853c-4082-a02a-a43bf17e15a4](https://user-images.githubusercontent.com/25897271/133136296-5cfa18ac-5a67-4d73-b58f-181cf6065dc3.png)
results in malformed url's
![133135838-478cd5c0-3588-4ec3-b6e9-2472eb71f174](https://user-images.githubusercontent.com/25897271/133136306-04f4092f-a33e-40c2-bad8-5f345c66cf2d.png)

**Comment by jessuppi** [comment]
Thanks for your feedback @Syncriix and sorry it took so long for us to respond here.

The code and functionality is now cleaned up a lot.

Tthe domain names are now inserted whenever `ss-install-wordpress-mu-plugins` is run to keep code simpler, and the PHP will preserve full URLs now which should make switching easier.

Ref: https://github.com/littlebizzy/slickstack/commit/25f637aaeaa50ab8b9de8ece6be823a5b99c5afb
Ref: https://github.com/littlebizzy/slickstack/commit/94d76b4873726c6729dad049c84af2ad9a772db9

For example, if you're on this page: 

    https://staging.example.com/wp-admin/admin.php?page=slickstack

...the "Production" switch link will now link here:

    https://www.example.com/wp-admin/admin.php?page=slickstack

...and so forth (production, staging, and dev). Much more predictable and useful functionality now, hopefully... 

I will close this for now, but comments are welcome.

**Comment by jessuppi** [comment]
P.S. thanks @backamblock for the improvements in the meanwhile.
