### ISSUE TITLE
Ubuntu 21.10  x64

### ISSUE THREAD

**Issue by heliomedia** [littlebizzy/slickstack#129]
Does it support 21.10  x64 for instalation slickstack ?

if not, which is the best version to use?

10x

**Comment by jessuppi** [comment]
Greetings @heliomedia 

Please review the documentation and description on the GitHub repo, current version is Ubuntu LTS 20.04 only right now.

Since we follow Ubuntu LTS releases, the next version we support will be: Ubuntu 22.04 (PHP v8.1).
