### ISSUE TITLE
Comparison with SpinupWP missing

### ISSUE THREAD

**Issue by wsoyka** [littlebizzy/slickstack#131]
The [Spinupwp comparison page](https://slickstack.io/compare/spinupwp) seems to be missing the feature comparison table.

**Comment by jessuppi** [comment]
Hello @wsoyka thanks for the feedback.

I'm not actually very familiar with SpinupWP so if you have any examples of which features compare and contrast with SlickStack please feel free to share here... for example, about their features or anything else really.

**Comment by jessuppi** [comment]
The comparison table is in progress and will be updated from time to time, future comments are welcome.

https://slickstack.io/alternative/spinupwp
