### ISSUE TITLE
what are these temp fixes for?

### ISSUE THREAD

**Issue by backamblock** [littlebizzy/slickstack#144]
so you got these in the ss-worker script
can you explain why you set those?
if my ss was installed with admin dashboard disables, will it install it?

```
## temp fix ##
sed -i "s|@SS_PILOT_FILE||g" /var/www/ss-config

sed -i "s|@SS_WORDPRESS_PLUGIN_BLACKLIST|true|g" /var/www/ss-config
sed -i "s|@WP_MULTISITE_STATUS|false|g" /var/www/ss-config
sed -i "s|@SS_WORDPRESS_ADMIN_DASHBOARD|true|g" /var/www/ss-config
sed -i "s|@SS_SWAPFILE_SIZE|2G|g" /var/www/ss-config
sed -i "s|@SS_LANGUAGE|en_US|g" /var/www/ss-config

```

**Comment by backamblock** [comment]
well.. nevermind.. these values don't exist anymore after install .. must be for older ss-installs that update...

**Comment by jessuppi** [comment]
Yes these are just fixes for SlickStack servers (e.g. hosting clients) who might have older `ss-config` files installed so we are just using the `ss-worker` to choose some default values for certain placeholders.
