### ISSUE TITLE
Polish WooCommerce skip cache slugs

### ISSUE THREAD

**Issue by szrejder** [littlebizzy/slickstack#157]
I was told on Discord to open an issue so you will be able to add Polish urls to skip the cache on Woo.

    ## POLISH - sensitive wordpress urls should always skip the cache
    if ($request_uri ~* "index.php|/konto.*|/koszyk.*|/zamowienie.*|/kontakt.*|/dashboard.*|/login.*|/moje-.*|/zamowienie.*|/profil.*|/register.*|/ustawienia.*|/view.*|/wc-api.*|/wp-admin.*|wp-.*.php") {
        set $skip_cache 1;
    }

I've changed urls already.

**Comment by jessuppi** [comment]
Awesome thanks @szrejder 

These changes have been made now to production, staging, development server blocks. An example:

Ref: https://github.com/littlebizzy/slickstack/commit/35cc7fa7ace2f59a5953cc1f365a31646604fcbc

Also bumped the SlickStack build to `MAR2022A`
