### ISSUE TITLE
Too Many Redirects after install.

### ISSUE THREAD

**Issue by Pross** [littlebizzy/slickstack#16]
After many attempts to install, the furthest I can get is too many redirects.

Trying to add Beaver Builder support for cache clearing as we have a customer who has installed this but after 3 hours battling with this ive had to give up and create a ticket.

Willing to share logins for debugging, its a temporary VPS anyway.

**Comment by jessuppi** [comment]
Hello Simon,

Hmm that sounds strange. We do offer private support for SlickStack servers if you sign up for our Membership at the Developer level: https://www.littlebizzy.com/members

Then we can login your servers and get you sorted anytime you have problems, as this sets up a client relationship between you and LittleBizzy. Thanks!

P.S. if you have any specific bugs you've found re: Beaver Builder feel free to paste here.

**Comment by Pross** [comment]
The issue our customer reported is the usual publish content and no caches are cleared, we have various actions in the plugin to clear various cache plugins.

$79 is too much just for testing a fix, i'll have a look at your cache mu plugin see if I hook into that.

**Comment by jessuppi** [comment]
Hah! We've spent thousands on releasing our free software, you come on here demanding even more free help and think $69 for a year of private support is too expensive? Get lost, bud ~

**Comment by Pross** [comment]
I'm sure our mutual customer has already paid both of us for support, I'll pass on your message.

**Comment by jessuppi** [comment]
LittleBizzy does not offer "support" to third party servers. We do offer consulting to developers or agencies who are running SlickStack servers if they sign up for Membership...

If you're the one who needs help, you need to pay. But your attitude is pretty revealing.
