### ISSUE TITLE
connection error via ssh after installation complete

### ISSUE THREAD

**Issue by zumrutk** [littlebizzy/slickstack#161]
dear author

i have successfully installed slickstack w/out any issue and my website running properly.  i wanted to connect via ssh port 2333 after installation completed with my newly created username spesific for ssh but getting error "permission denied" and does not accept my password that installation referred.
could you please help me for this situation to fix and get logged in again.

thanks

**Comment by jessuppi** [comment]
Hello @zumrutk 

This is more of a Support question which is better addressed in our chat rooms, such as Discord. If you have a bug to report or feature suggestion you can use GitHub to submit an Issue.

"Permission denied" usually means the username/password is incorrect. "Connection refused" is usually more related to the port number being incorrect.

For best results please use port 22 to avoid conflicts with certain cloud providers (like AWS).
