### ISSUE TITLE
Development nginx server block uses staging keyword

### ISSUE THREAD

**Issue by BHare1985** [littlebizzy/slickstack#166]
I installed both dev and staging support. After installation `/var/www/sites/development` used:

```
server_name                 staging.mydomain.com;
root                        /var/www/html/staging;
```

which is incorrect.

Bug introduced here: https://github.com/littlebizzy/slickstack/commit/0870d8ff65ba0498b82d7ed283800e0ab80cde46

**Comment by jessuppi** [comment]
Thanks for reporting @BHare1985 

This is now fixed: https://github.com/littlebizzy/slickstack/commit/439a5b1cf45acf06d6691ce476d218c3d3ed5dc2
