### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach() in

### ISSUE THREAD

**Issue by bari86** [littlebizzy/slickstack#172]
A newly installed SS would show this error. Not sure why.

`[15-Aug-2022 13:15:45 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-admin/includes/plugin.php on line 1779`

**Comment by jessuppi** [comment]
Duplicate of https://github.com/littlebizzy/slickstack/issues/30
