### ISSUE TITLE
Migration slickstack between VPS to VPS

### ISSUE THREAD

**Issue by hargums** [littlebizzy/slickstack#187]
Hallo, i already try your slickstack couple of days, i consider to donate ASAP, but I have some problem with it like 
1. Migration from VPS to another VPS there no documentation specifically for slickstack, I think with easier installation and seamless, there will more easier for migration process too
2. very hard to make my wordpress available to access by its IP address, example I had www.example.com with static IP VPS 123.456.789 i want to my wordpress can access through its domain name and it's ip address too and it's not solved. And 
3. I had very high CPU from mysqld service and i must reconfigure my.cnf with proper config or I consider to change it with mariadb that run smooth before slickstack but it will had another problem especially if I run ss install again if I change it from mysqld to mariadb

I hope there any documentation about it specifically for slickstack system

**Comment by jessuppi** [comment]
@hargums Thanks for your participation here, but these are more general support questions.

Please consider sponsoring SlickStack and asking these questions in our Discord channel instead, since GitHub is more reserved for bug reports and specific feature requests.
