### ISSUE TITLE
Install freeze on Running ss-install-redis-packages... 

### ISSUE THREAD

**Issue by willemkuijpers** [littlebizzy/slickstack#189]
Hi,

The installation gets a freeze when running on

Running ss-install-redis-packages... 

after that the installation is freezing..

System ubuntu 22.04 lts

**Comment by jessuppi** [comment]
Thanks for reporting! @willemkuijpers 

Looks like we missed fixing a few instances of `apt` to be the new `ss_apt` function, patched now:

https://github.com/littlebizzy/slickstack/commit/4ab06ac91a106a173e8997d148d3341b611973f2

**Comment by jessuppi** [comment]
On a side note I think we will change from Redis to Memcached for better stability, I have seen several WordPress sites have frozen Redis processes in the past, among other issues, it's just overly complex seems.

Ref: https://github.com/littlebizzy/slickstack/issues/183
