### ISSUE TITLE
Website very slow loading inside apps ios

### ISSUE THREAD

**Issue by willemkuijpers** [littlebizzy/slickstack#190]
Hi,

If you send a link with snapchat or Whatsapp the website is very slow loading with slick stack.

I tried to fix it but i can't find any reason why this is happening.

On Android it working normally but on iOS its fucked up.

**Comment by jessuppi** [comment]
Thanks for reporting @willemkuijpers 

However I have no idea what could be causing that, or if it's site-specific to your domain, etc. We would probably need more information to try and debug this, or it's just an "Apple problem" like other issues with Safari.

**Comment by jessuppi** [comment]
@willemkuijpers You can sponsor us for $1/month and join our private Discord server if you like? That is the only place where I deal with private SlickStack discussions currently.

For now I'm going to close this issue because it's likely not from SlickStack bugs, thank you --
