### ISSUE TITLE
SS_ADMINER_PUBLIC="false" does not work as intended.

### ISSUE THREAD

**Issue by NathanAdhitya** [littlebizzy/slickstack#196]
# Issue
On  version APR2023K, SS_ADMINER_PUBLIC set to "false" still exposes Adminer to the public web.

**Comment by jessuppi** [comment]
Related: https://github.com/littlebizzy/slickstack/issues/73

**Comment by jessuppi** [comment]
Perhaps this is another feature that could be moved to our new Nginx includes approach, like:

```
/var/www/sites/includes/adminer.conf
```

**Comment by jessuppi** [comment]
If we end up doing something like:

https://wordpress.org/plugins/db-access-adminer/

Where it requires WP Admin authentication, the entire issue might be moot.

**Comment by jessuppi** [comment]
Some patches:

https://github.com/littlebizzy/slickstack/commit/fd74e7a4f9c295b406b84dd2d896aafa10868c9c

https://github.com/littlebizzy/slickstack/commit/865024f88242e64f941f0fba5e561130126abf83

**Comment by jessuppi** [comment]
These patches (above) are temporary, because they delete the `adminer.php` file in case `SS_ADMINER_PUBLIC` is set to `false` in your ss-config. Later on, we should consider a separate Nginx file for Adminer too.

**Comment by jessuppi** [comment]
New sub-module in progress:

https://github.com/littlebizzy/slickstack/blob/master/modules/nginx/includes/adminer-conf.txt

**Comment by jessuppi** [comment]
We could probably also hide the Database tab in the SlickStack WP Admin Dashboard if this is set to false, that's something that a few developers had asked about.

**Comment by jessuppi** [comment]
Update: this option in ss-config is now called `ADMINER_PUBLIC`
