### ISSUE TITLE
Recommended cloud VPS server providers (WP Speedtest repo)

### ISSUE THREAD

**Issue by szepeviktor** [littlebizzy/slickstack#21]
Back then it was my liking, nice UI, low prices... than came 2 years of **measurements**

See 160 server providers https://github.com/szepeviktor/wordpress-speedtest and [reconsider](https://github.com/szepeviktor/wordpress-speedtest/blob/master/README.md#how-to-choose-vps-provider) using popular providers.

**Comment by szepeviktor** [comment]
![image](https://user-images.githubusercontent.com/952007/60402961-284cce80-9b97-11e9-9cc4-88c4f5a18941.png)

You may own a turbo-mouse 🐁

**Comment by jessuppi** [comment]
Thanks for the reference on cloud providers.

Please keep Issues on-topic and don't post personal information, thank you --

**Comment by szepeviktor** [comment]
Okay.

After 2 years of searching I've concluded that popular ones (Linode, DO, Vultr) won't help me when there's a problem, and big ones (Amazon, MS, Google) will do the same.

So all my client are at @UpCloudLtd

**Comment by jessuppi** [comment]
Keep in mind that SlickStack recommends (requires, really) KVM cloud servers. Also keep in mind that most any quality provider will eventually start growing, hiring new employees, etc... and scaling is difficult for many reasons.

We definitely try to support smaller providers whenever possible, although some of them don't respond after we reach out to them about SlickStack tutorials and such.

Any providers reading this, please feel free to get in touch with us to be listed here:

https://slickstack.io/hosting
