### ISSUE TITLE
ss-config had a build version update, but ss-update-config didn't

### ISSUE THREAD

**Issue by vivianedias** [littlebizzy/slickstack#212]
I'm trying to run `ss-install` again on my server, but I'm unable to because I think `ss-update-config` build version wasn't updated to "MAR2024ZZZZ" while `ss-config-example` was. 

I'm currently getting the following error after `ss-update-config`: 

```bash
Exiting ss-update-config: There is a version mismatch between this script and public mirrors...
```

And yes, I have ran `ss-check` to sync my local `ss-update-config` file with the remote.

**Comment by icodeforlove** [comment]
This is most likely because @jessuppi does not use version tags. This project should be using Semantic Versioning with tags, and a update process which utilizes this.

This would help avoid issues like this where you end up trying to update against a master only branch where the project owner commits to like a personal project.

**Comment by jessuppi** [comment]
Hey @vivianedias 

Thanks for reporting, yes this was done on purpose to prevent new installations right now due a bug we are discussing on the Discord server, you are welcome to join there.

**Comment by icodeforlove** [comment]
> Hey @vivianedias
> 
> Thanks for reporting, yes this was done on purpose to prevent new installations right now due a bug we are discussing on the Discord server, you are welcome to join there.


Addressing this issue could be more effectively managed through the adoption of a development/master branch workflow.

Limiting installations and updates seems counterproductive. It's worth considering allocating additional time to align with best practices in Git usage.

Additionally, reevaluating the current approach of committing each file separately with nondescriptive commit messages could lead to significant improvements. Transitioning to meaningful git commit messages is recommended.

Such changes would enhance the project's accessibility to collaborators and clarify project developments for its users.

**Comment by jessuppi** [comment]
Bug fixed causing `openssl.conf` to not copy over properly sometimes, by replacing `ss_cp` with `ss_mv` inside the ss-install-nginx-ssl script and we should continue to do that for most other scripts too.

Installations are working now as of build `APR2024A`
