### ISSUE TITLE
Can't get it to work out of the box?

### ISSUE THREAD

**Issue by foguii** [littlebizzy/slickstack#213]
Hi there, I'm trying to set this up on digital ocean for a staging site. 

I'm using mycustomdomain.com as TLD and staging.mycustomdomain.com as the domain. I don't really need to indicate anything else. Out of the box, the website isn't connecting... the server times out. I suspect the subdomain is the issue.

How can I switch over to let's encrypt?

**Comment by jessuppi** [comment]
Hello @foguii 

It might be a domain conflict, as `staging.example.com` and `dev.example.com` are reserved names in SlickStack, I suggest trying another name for your server instead. You can also reinstall a few times as needed, no data is lost.

For general questions please join our Discord server, thanks!
