### ISSUE TITLE
Can't install due to 403

### ISSUE THREAD

**Issue by alltrad3s** [littlebizzy/slickstack#217]
I initially couldn't access the site from my country, used US VPN and was able to. Then, when I used a AWS Lightsail instance. I got 403 when I tried to install. Couldn't find where to post this so I apologize if that shouldn't have been posted here.

**Comment by jessuppi** [comment]
Hello @alltrad3s you can post general support questions to our Discord or public forums.

But if this is a bug we want to know. Are you using Cloudflare? Have you reviewed all your Cloudflare settings to ensure that you don't have a Country block in the WAF firewall or something like that?

Have you also reviewed the firewall options provided by your cloud provider, AWS in this case?

**Comment by jessuppi** [comment]
Closing this due to no response, feel free to follow up later.
