### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by vivianedias** [littlebizzy/slickstack#219]
Hey folks,

The website is down. I was going to startup slick stack on a server and wanted to checkout the required specs. 

Any news on when is going back?

**Comment by jessuppi** [comment]
Hey @vivianedias the website is still loading fine: https://slickstack.io

It's possible you have the same exact device profile as a hacker we recently blocked from our server who had been coordinating DDOS attacks against the site.

You can try another device if possible and it should load fine, thanks!
