### ISSUE TITLE
Check Bash scripts

### ISSUE THREAD

**Issue by szepeviktor** [littlebizzy/slickstack#22]
[shellcheck](https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz) taught me a lot

```bash
find . -type f "(" -name "*.txt" -or -name "*.sh" ")" -exec grep -Fxnl '#!/bin/bash' "{}" ";" | xargs -L1 shellcheck -e SC1091
```

**Comment by jessuppi** [comment]
Did you find any specific bug or error here?

Please keep in mind this is not a general discussion forum, thank you --

**Comment by szepeviktor** [comment]
It is about seeing the benefit of shellcheck.
If you run the above command you'll see many dangerous ones.

I am [not a ss user](https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup.sh).

**Comment by szepeviktor** [comment]
@jessuppi See the joy 🎉 in https://github.com/littlebizzy/slickstack/issues/9#issuecomment-507171292
