### ISSUE TITLE
uncomplicate the mysql_secure_installation part

### ISSUE THREAD

**Issue by zardoz-bzar** [littlebizzy/slickstack#23]
https://github.com/zardoz-bzar/clearlinux-ecommerce/commit/92e31b35156fe98dcf2f7fda047d4b032dca3335#diff-4aab37fabb3b33d71273effeab104bb7

Gave you a shout out in the commit message. Check my bits at the bottom below line 83 for removing an running the actual commands mysq_secure_installation runs, but is more reliable due to not using expect (in case the patterns change in a release). 

Cheers!

**Comment by jessuppi** [comment]
Wow thanks mate, appreciate that.

I'm copy pasting your code snippet below for reference:

    systemctl enable mariadb
    systemctl start mariadb
    #mysql_secure_ins-whatever is a garbage script
    #run the same commands it does, but without an expect wrapper
    #this is a cloud cattle car, not a multiuser system
    export PASS=MYVAL
    mysql -uroot -e "UPDATE mysql.user SET Password=PASSWORD('$PASS') WHERE User='root';"
    mysql -uroot -p$PASS -e "FLUSH PRIVILEGES;"
    mysql -uroot -p$PASS -e "DELETE FROM mysql.user WHERE User='';"
    mysql -uroot -p$PASS -e "DROP DATABASE IF EXISTS test;"
    mysql -uroot -p$PASS -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'"
    mysql -uroot -p$PASS -e "FLUSH PRIVILEGES;"
    #this disabled everything but remove root login, which in a private VPC you might want on
    #but here's the part that does it, ripped out of that script 
    #mysql -uroot -p$PASS -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
    #mysql -uroot -p$PASS -e "FLUSH PRIVILEGES;"

Yah I hate the expect approach too, but didn't know of a better method... MySQL in general seems to present various challenges in Bash scripting.

Will review this, thanks :)

**Comment by jessuppi** [comment]
We are no longer using `expect` or janky guess-and-check for MySQL installation, which is now in it's own script. Although it's still being perfected, interested users can review the script here:

https://github.com/littlebizzy/slickstack/blob/master/ss-install-mysql.txt

It is now included as part of the `ss-install` process.

The focus is now on supporting MySQL 8.0.x and accompanying challenges like password validation, `auth_socket` etc.
