### ISSUE TITLE
timezone 

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#29]
## set timezone ##
if [[ -z "$SS_TIMEZONE" ]]; then 
    timedatectl set-timezone UTC
else 
    timedatectl set-timezone @SS_TIMEZONE
fi

I believe it should be read $SS_TIMEZONE since its not sed'ed

**Comment by jessuppi** [comment]
Thanks @Bronislawsky,

I assume you are referring to the `ss-install` script only, it's now fixed:

https://github.com/littlebizzy/slickstack/commit/b90b85737eccec92043274b758baaa738c568fb8
