### ISSUE TITLE
Not an issue but,..

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#32]
On  http://mirrors.slickstack.io/ubuntu/
       the link http://mirrors.slickstack.io/ubuntu/sysctl-conf.txt
       should be http://mirrors.slickstack.io/ubuntu/sysctl.txt

**Comment by jessuppi** [comment]
@Bronislawsky thanks for reporting, it's now fixed:

https://github.com/littlebizzy/slickstack/blob/master/ubuntu/index.md

https://github.com/littlebizzy/slickstack/commit/7ae65d524e9c80aae7af863ee53ab6f0e764cff0
