### ISSUE TITLE
ss-update

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#33]
SS_MU_PLUGINS get broken up ss-update because it set SS_TYPE instead of SS_MU_PLUGINS

if [[ -n "$SS_MU_PLUGINS" ]]; then
sed -i "s|\(^SS_MU_PLUGINS=\).*|**SS_TYPE**=\"$SS_MU_PLUGINS\"|g" /tmp/ss-config
fi

**Comment by jessuppi** [comment]
@Bronislawsky thanks for reporting, this is now fixed:

https://github.com/littlebizzy/slickstack/blob/master/ss-update.txt

https://github.com/littlebizzy/slickstack/commit/b3d5c0a01daf2cfbb2046d89553947b02fc4aa17
