### ISSUE TITLE
ss-install

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#37]
Needs to be updated

if [[ "${UBUNTU_VERSION}" != "20.04" ]]; then
    echo -e "\e[93mSlickStack is d**esigned for Ubuntu 18.04, but this serv**er is running Ubuntu ${UBUNTU_VERSION}.\e[0m" >&2
    exit 1
fi

**Comment by jessuppi** [comment]
@Bronislawsky thanks, this is now fixed:

https://github.com/littlebizzy/slickstack/blob/master/ss-install.txt

Ref: https://github.com/littlebizzy/slickstack/commit/abc54f9fb669d3be048da2be1faba1e5b538b91d
