### ISSUE TITLE
SSL and other questions

### ISSUE THREAD

**Issue by fabianskibr** [littlebizzy/slickstack#4]
during the installation I received these errors and then it stops, wordpress is installed but without the SSL certificate.

I also lose FTP and SSH access even using the username and password that I put in the configuration.

About redis: Is it necessary to use a plugin for it to work?

Thank you in advance

```
The user `www-data' is already a member of `wordpress'.
chown: cannot access '/var/www/4-cron-daily': No such file or directory
chown: cannot access '/var/www/5-cron-weekly': No such file or directory
chown: cannot access '/var/www/6-cron-monthly': No such file or directory
chown: cannot access '/var/www/7-cron-sometimes': No such file or directory
chmod: cannot access '/var/www/4-cron-daily': No such file or directory
chmod: cannot access '/var/www/5-cron-weekly': No such file or directory
chmod: cannot access '/var/www/6-cron-monthly': No such file or directory
chmod: cannot access '/var/www/7-cron-sometimes': No such file or directory
find: ‘/var/www/html/uploads/’: No such file or directory
mkdir: cannot create directory ‘/var/www/html/wp-content/temp’: File exists
chown: cannot access '/var/www/html/wp-content/blacklist.txt': No such file or directory
chmod: cannot access '/var/www/html/wp-content/blacklist.txt': No such file or directory
mkdir: cannot create directory ‘/var/www/logs’: File exists
mkdir: cannot create directory ‘/var/run/php’: File exists
mkdir: cannot create directory ‘/var/www/cache’: File exists
chown: cannot access '/etc/nginx/cache': No such file or directory
chmod: cannot access '/etc/nginx/cache': No such file or directory
find: ‘/etc/nginx/cache/’: No such file or directory
find: ‘/etc/nginx/cache/’: No such file or directory
chown: cannot access '/etc/ssl/nginx.pem': No such file or directory
chmod: cannot access '/etc/ssl/nginx.pem': No such file or directory
chown: cannot access '/etc/php/7.0/fpm/php.ini': No such file or directory
chown: cannot access '/etc/php/7.0/fpm/php-fpm.conf': No such file or directory
chown: cannot access '/etc/php/7.0/cli/php.ini': No such file or directory
mkdir: cannot create directory ‘/var/run/mysqld’: File exists
mkdir: cannot create directory ‘/var/run/redis’: File exists

```

**Comment by jessuppi** [comment]
What commands did you use to install? Looks like maybe you installed in the wrong directory.

You may need to reboot the server (and/or `service ssh restart`) to get SFTP working. Rebooting after a successful SlickStack install is a good idea, we will update the docs.

Yes you can use any Redis-supporting WordPress object cache plugins such as:

https://wordpress.org/plugins/redis-cache/

**Comment by fabianskibr** [comment]
With user root i use the commands to install

sudo mkdir /var/www/ && sudo chown root:root /var/www/ && sudo chmod 755 /var/www/
sudo nano /var/www/ss-config (with my configs)
cd /var/www/ && sudo wget -O ss slick.fyi && sudo chmod 755 ss && sudo bash ss

the same commands as the installation tutorial, I did not change any directory

thanks

**Comment by jessuppi** [comment]
All I can think of is that your install process didn't complete fully. You can try installing again on a fresh server, make sure it has at least 2GB RAM and Ubuntu.

You can also link to Pastebin your ss-config file content (remove sensitive info).

**Comment by fabianskibr** [comment]
was a vps with 1gb of ram, is not it compatible?

**Comment by jessuppi** [comment]
Did you even read the documentation? https://github.com/littlebizzy/slickstack

If you require step-by-step support please become a Member:

https://www.littlebizzy.com/members

**Comment by iub98** [comment]
I didn’t want to create another issue, so I’m posting this in here.  Excuse the noob question but can I use the script to install multiple sites on a single vps?  I’ve installed a single site without a problem, but am struggling with creating a second site on the same Vps. Thank you for this awesome installer btw.  Scared of runcloud and server pilot should they get hacked or go down.

**Comment by jessuppi** [comment]
>  Excuse the noob question but can I use the script to install multiple sites on a single vps? 

Read the documentation please, SlickStack is for single sites only.
