### ISSUE TITLE
ss-update results in 403 errors after reboot

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#44]
Hi! 
I have a VM that I try to always keep up to date with ss so I can make sure when I roll updates
on production VMs everything is ok..

Here is a problem I encounter
when I run ./ss-update & reboot
I be getting 403 everywhere.

The work around I have found is running ./ss-perms  and then ./ss-restart upon reboot
And it seems to fix it.

Thanks

UPDATE

this line` find /var/www/html/ -type f -exec chmod 6664 {} \;` remove the 403 but the site is blank, 
I dont know exactly which other blocks is responsible to restore the site.. I will investigate a little later

**Comment by jessuppi** [comment]
@Bronislawsky Thanks again for reporting, I've added `source /var/www/ss-perms` to `ss-update` toward the bottom of the script (before services restart) which should help.

Ref: https://github.com/littlebizzy/slickstack/commit/0c9600e6595efb716d8c67cf5c9b1006d378c2cc

**Comment by Bronislawsky** [comment]
Thank you @jessuppi , I just tried and it works perfectly now, no more 403.
