### ISSUE TITLE
Unable to connect to Google Cloud instance after installation

### ISSUE THREAD

**Issue by amankapoor** [littlebizzy/slickstack#5]
Hey,

I tried installing this three or four times but in every case, I couldn't connect back to the instance on port 22 using SSH window system of Google Cloud.

It says ```Connection Failed: We are unable to connect to the VM on port 22. [Learn more](https://cloud.google.com/compute/docs/ssh-in-browser#ssherror) about possible causes of this issue.```

In my earlier tries, I was unable to run ```sudo reboot``` after the installation, but then I fixed it by creating a password before beginning the installation.

I tried ```sudo reboot``` and ```service ssh restart```, but to no avail.

I am doing it on Google Cloud and accessing the terminal by clicking on SSH button which opens the terminal in a new popup window.

Thanks.

**Comment by jessuppi** [comment]
Did you read the documentation?

Why are you using Google Cloud when its not supported?
