### ISSUE TITLE
wp-config :: WP_LANG

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#55]
```
I noticed that the default locale for WP_LANG is en-US.
should not it be en_US  instead ?
```

**Comment by jessuppi** [comment]
Thanks @Bronislawsky 

We had initially put a few language related items in `wp-config.php` temporarily while research continued, but after looking into it more carefully it seems `WPLANG` is no longer supported, and even including `wplang.php` does not seem common anymore either so I've removed both of these from our boilerplate and `ss-config` as well.

Ref: https://github.com/littlebizzy/slickstack/blob/master/wordpress/wp-config.txt
Ref: https://github.com/littlebizzy/slickstack/blob/master/ss-config-sample.txt

If anyone has follow up comments on this please comment below, or open a new Issue re: language, thanks!

Ref: https://wplang.org/translation-plugins-languages/
