### ISSUE TITLE
WP uploads folder bug

### ISSUE THREAD

**Issue by hxinen** [littlebizzy/slickstack#6]
Hi! First of all, I would want to thank you for a great work.

It was working perfectly fine, but I had to reinstall ss.

After which, I noticed that my uploads url are not correct - 
https://i.imgur.com/OAGUmAm.png

Removing the following fixed it.

define('WP_CONTENT_URL', 'https://truelocal.ph/wp-content/');
define('WP_PLUGIN_URL', 'https://truelocal.ph/wp-content/plugins/');
define('UPLOADS', 'https://truelocal.ph/wp-content/uploads/');

**Comment by jessuppi** [comment]
Whoops! Thanks for reporting this... we should have researched the format more carefully before adding those new snippets a few days ago. It should now be fixed, as below:

    define('WP_HOME', 'https://@DOMAIN');
    define('WP_SITEURL', 'https://@DOMAIN');
    define('WP_CONTENT_URL', 'https://@DOMAIN/wp-content');
    define('WP_PLUGIN_URL', 'https://@DOMAIN/wp-content/plugins');
    define('UPLOADS', 'wp-content');

If you re-run the `ss-install` it should work correctly now.

Ref: https://github.com/littlebizzy/slickstack/blob/master/wordpress/wp-config.txt

**Comment by jessuppi** [comment]
@hxinen Also if you're interested in being listed:

https://slickstack.io/experts/

I'll leave this issue open for bit longer but I think it should be fixed, cheers!
