### ISSUE TITLE
Let's Encrypt removed from Nginx (switched back to OpenSSL)

### ISSUE THREAD

**Issue by Bronislawsky** [littlebizzy/slickstack#62]
```

Hi!

 Something went wrong with certbot this morning..
All the sitesusing certbot were switched back to self signed cert

    ssl_certificate /etc/ssl/fullchain.pem;
    ssl_certificate_key /etc/ssl/privkey.pem;

/etc/ssl/fullchain.pem -> /etc/letsencrypt/live/xxxxxxx/fullchain.pem
the symlink was missing.

I ran ss-encrypt manually to fix the issue

```

**Comment by jessuppi** [comment]
Thanks for reporting @Bronislawsky 

It looks like we need to have `ss-encrypt` run at the bottom of `ss-install-nginx` script to avoid this in the future:

Ref: https://github.com/littlebizzy/slickstack/commit/71e43599a8155dc256692a33df6c1586e3421b90

Here's a temporarily fix until those scripts can be better organized.

**Comment by Bronislawsky** [comment]
Great!

   Just make sure certbot is not ran too often because there is a weekly limit of certificates you can get per domain per week I believe

**Comment by gabrielstuff** [comment]
hello !
Got the same issue during the install. 
After that, I run certbot two times and it finally managed to resolve the http-01 challenge. I've been running : `certbot certonly --nginx`

Will see how it goes with renewal.

I've made a fresh install on a `ubuntu Focal Fossa (20.04 LTS)` as root, running: `cd /tmp/ && wget -O ss slick.fyi && bash ss
`

**Comment by jessuppi** [comment]
I believe these are 2 different causes, for @Bronislawsky it was just the Nginx config needed to re-add the Let's Encrypt rules as previously our `ss-install-nginx` installer defaulted to OpenSSL without checking for Let's Encrypt in `ss-config`.

For @gabrielstuff I'm not sure why you're manually running `certbot` commands, this is not necessary for SlickStack and will quite possibly mess up your stack configuration.

Always use `sudo bash ss-encrypt` in SlickStack when you want to renew/reinstall your SSL certs 👍
