### ISSUE TITLE
undefined constant SS_DASHBOARD

### ISSUE THREAD

**Issue by corzel** [littlebizzy/slickstack#65]
Hi,
New php warning:

> `PHP Warning: Use of undefined constant SS_DASHBOARD - assumed 'SS_DASHBOARD' (this will throw an Error in a future version of PHP) in /var/www/html/wp-content/mu-plugins/xxx-notices.php on line 25`

Regards.

**Comment by jessuppi** [comment]
Sorry for the long delay @corzel 

This was fixed a while back, and another note, we no longer use booleans in ss-constants.php or xxx-common.php in order to avoid potential fatal errors (even though that's not related here). Thanks!
