### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by riyas-rawther** [littlebizzy/slickstack#69]
Notice: Undefined variable: modified in /var/www/html/wp-content/mu-plugins/clear-caches/helpers/updater.php on line 136 Notice: Undefined variable: modified in /var/www/html/wp-content/mu-plugins/dashboard-cleanup/helpers/updater.php on line 136 Notice: Undefined variable: modified in /var/www/html/wp-content/mu-plugins/disable-gutenberg/helpers/updater.php on line 136 Notice: Undefined variable: modified in /var/www/html/wp-content/mu-plugins/force-https/helpers/updater.php on line 136

**Comment by jessuppi** [comment]
Hello thanks for reporting @riyas-rawther 

This issue already exists, so I will close this issue, thanks!

Ref: https://github.com/littlebizzy/slickstack/issues/59
