### ISSUE TITLE
Issue: 403 Error

### ISSUE THREAD

**Issue by LCBO** [littlebizzy/slickstack#77]
Hello,
I tried already 3 times to install it on Ubuntu 20.04 and I still get the 403 Error. In cloudflare the SSL is set on FULL. 
I rebooted the server and nothing.

**Comment by distich** [comment]
Dealing with the same. Any ideas?

**Comment by LCBO** [comment]
In such case, it is because of some recent changes in the stack. I am trying to reinstall. The fourth time.

**Comment by LCBO** [comment]
This was modified 8 days ago: https://github.com/littlebizzy/slickstack/blob/master/nginx/default-single-site.txt

**Comment by jessuppi** [comment]
Hello folks please try running `sudo bash /var/www/ss-perms` and it should fix it, we have a bug in the new script for installing WordPress Core `ss-install-wordpress-core` which we are fixing now.

**Comment by LCBO** [comment]
I just tried but nothing:

`SS-PERMS: Resetting all file permissions across entire SlickStack server...
addgroup: The group `wordpress' already exists.
The user `robin' is already a member of `wordpress'.
The user `www-data' is already a member of `wordpress'.
The user `robin' is already a member of `www-data'.
chown: cannot access '/var/www/html/staging/wp-content/blacklist.txt': No such file or directory
chmod: cannot access '/var/www/html/staging/wp-content/blacklist.txt': No such file or directory
chown: cannot access '/var/www/html/dev/wp-content/blacklist.txt': No such file or directory
chmod: cannot access '/var/www/html/dev/wp-config.php': No such file or directory
chmod: cannot access '/var/www/html/dev/wp-content/blacklist.txt': No such file or directory
chown: cannot access '/var/www/html/staging/wp-content/functions.php': No such file or directory
chmod: cannot access '/var/www/html/staging/wp-content/functions.php': No such file or directory
chmod: cannot access '/var/www/html/staging/wp-content/blacklist.txt': No such file or directory
chown: cannot access '/var/www/html/dev/wp-content/mu-plugins': No such file or directory
chown: cannot access '/var/www/html/dev/wp-content/functions.php': No such file or directory
find: ‘/var/www/html/dev/wp-content/mu-plugins/’: No such file or directory
find: ‘/var/www/html/dev/wp-content/mu-plugins/’: No such file or directory
chmod: cannot access '/var/www/html/dev/wp-content/mu-plugins/autoloader.php': No such file or directory
chmod: cannot access '/var/www/html/dev/wp-content/mu-plugins/xxx-common.php': No such file or directory
chmod: cannot access '/var/www/html/dev/wp-content/object-cache.php': No such file or directory
chmod: cannot access '/var/www/html/dev/wp-content/functions.php': No such file or directory
chmod: cannot access '/var/www/html/dev/wp-content/blacklist.txt': No such file or directory
`

**Comment by jessuppi** [comment]
What is the output when you run `sudo nginx -t` to test current Nginx configuration? Also recent lines from `nginx.log` and/or `error.log` under the `/var/www/logs` directory could be useful --

**Comment by LCBO** [comment]
I will install once again and revert back.

**Comment by LCBO** [comment]
root@racknerd-023acf:/tmp# sudo nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by jessuppi** [comment]
What cloud networks are you guys installing on? What results do you see with `sudo bash /var/www/ss-restart`

**Comment by LCBO** [comment]
here they are:Restarting clamav-freshclam (via systemctl): clamav-freshclam.service.
Restarting redis-server (via systemctl): redis-server.service.
Restarting php7.4-fpm (via systemctl): php7.4-fpm.service.
Restarting nginx (via systemctl): nginx.service.
Restarting mysql (via systemctl): mysql.service.
Reloading ufw configuration (via systemctl): ufw.service.
Restarting ufw (via systemctl): ufw.service.

**Comment by LCBO** [comment]
YES, on vultr it works !!!
Why it doest work on that server. It is a KVM one ? How should I make it work

**Comment by distich** [comment]
Mine is on RackNerd as well, same issue. That's odd.

**Comment by jessuppi** [comment]
I'm not sure it is possible something in their Ubuntu packages is conflicting. Customers from Dedimax also:

Ref: https://github.com/littlebizzy/slickstack/issues/64

We have not had time to test RackNerd or Dedimax but try to pay close attention to your shell screen during `ss-install` and see if you notice any weird messages or errors, esp. red-colored messages.

**Comment by LCBO** [comment]
I solved it I thing.
Install rsync

**Comment by jessuppi** [comment]
Okay we will need to add a snippet to install `rsync` perhaps in the `ss-install` if package not exists.

**Comment by jessuppi** [comment]
Okay I've added `apt install rsync` to the `ss-install-misc` script for now. This is very strange because I had though all Ubuntu ISOs included it by default already so I'm not sure why some cloud networks have it removed?

Ref: https://github.com/littlebizzy/slickstack/commit/e6164c5908e5acd384b42f3fc8a0ea4889924dab

**Comment by jessuppi** [comment]
Closing this out, but if anyone finds other missing "utility" apps on their cloud network please comment below or create a new Issue that mentions your web hosting and which apps need to be added to our installer, thanks!
