### ISSUE TITLE
Adminer Not Installed or Not Working

### ISSUE THREAD

**Issue by wponramp** [littlebizzy/slickstack#91]
Recently installed SS on a new Digital Ocean server. Adminer does not work.

**Comment by jessuppi** [comment]
Thanks for your feedback @wponramp

However, without more information this is not helpful. What exactly is not working? GitHub Issues are really for bug reports and feature requests, not general user help. If you have an error or anything more specific it would be great.

**Comment by wponramp** [comment]
When I try to load Adminer in my browser, a message appears saying, "An error occurred trying to load the resource." This same error has shown on the last two servers installed on Digital Ocean servers.

**Comment by jessuppi** [comment]
I believe maybe this was occurring due to failed `wget` processes or incorrect/missing file during our GitHub updates... I'm not really sure but I haven't seen this happen or heard anyone report this again since this Issue.

Anyway feel free to comment again if you see this happen again, thanks!

**Comment by jessuppi** [comment]
Update: I've added some file validation checks to `ss-install-adminer` for better stability: https://github.com/littlebizzy/slickstack/commit/da966af765937379339c779512b702ae7cb73ff9
