### ISSUE TITLE
Bug in ss-functions preventing ss core bash scripts from functioning

### ISSUE THREAD

**Issue by corzel** [littlebizzy/slickstack#93]
The ss scripts are not working. 
```
sudo bash ss-purge
/var/www/ss-functions: line 769: unexpected EOF while looking for matching `"'
/var/www/ss-functions: line 875: syntax error: unexpected end of file

```
Is the same for ss-check, ss-worker

**Comment by jessuppi** [comment]
Thanks @corzel yes we had a bug in `ss-functions` (a missing quotation mark... always the killer). We have a temporary patch added to the `01-cron-often` cron job that should run on all SS servers within the next 6 hours or so...

Ref: https://github.com/littlebizzy/slickstack/commit/e188921595d68b27948cff550415f62afe7c662b
